// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const callbacks = new Set<(event: any, session: any) => void>();

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  const client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });

  if (typeof window !== 'undefined') {
    const originalGetSession = client.auth.getSession.bind(client.auth);
    client.auth.getSession = async () => {
      if (localStorage.getItem("mock_session") === "true") {
        const mockEmail = localStorage.getItem("mock_email") || "mario.alcocer1997@gmail.com";
        const mockName = localStorage.getItem("mock_name") || "Mario Alcocer (Mock Admin)";
        const mockToken = localStorage.getItem("mock_token") || "mock-admin-token";
        const mockUserId = localStorage.getItem("mock_user_id") || "mock-admin-id";
        return {
          data: {
            session: {
              access_token: mockToken,
              expires_at: Math.floor(Date.now() / 1000) + 24 * 3600,
              user: {
                id: mockUserId,
                email: mockEmail,
                user_metadata: { full_name: mockName }
              }
            } as any
          },
          error: null
        };
      }
      return originalGetSession();
    };

    const originalGetUser = client.auth.getUser.bind(client.auth);
    client.auth.getUser = async (jwt?: string) => {
      const mockToken = localStorage.getItem("mock_token") || "mock-admin-token";
      if (localStorage.getItem("mock_session") === "true" || jwt === mockToken || jwt === "mock-admin-token") {
        const mockEmail = localStorage.getItem("mock_email") || "mario.alcocer1997@gmail.com";
        const mockName = localStorage.getItem("mock_name") || "Mario Alcocer (Mock Admin)";
        const mockUserId = localStorage.getItem("mock_user_id") || "mock-admin-id";
        return {
          data: {
            user: {
              id: mockUserId,
              email: mockEmail,
              user_metadata: { full_name: mockName }
            } as any
          },
          error: null
        };
      }
      return originalGetUser(jwt);
    };

    client.auth.signInWithPassword = async (credentials) => {
      try {
        // Carga dinámica de la función de servidor para evitar ciclos de importación en bundling
        const { loginServerFn } = await import("@/lib/auth.functions");
        const res = await loginServerFn({
          data: {
            email: credentials.email,
            password: credentials.password
          }
        });

        if (!res || !res.session) {
          throw new Error("No session returned from server");
        }

        const { access_token, user } = res.session;

        localStorage.setItem("mock_session", "true");
        localStorage.setItem("mock_token", access_token);
        localStorage.setItem("mock_email", user.email);
        localStorage.setItem("mock_name", user.user_metadata.full_name);
        localStorage.setItem("mock_user_id", user.id);

        setTimeout(() => {
          for (const cb of callbacks) {
            cb("SIGNED_IN", res.session);
          }
        }, 0);

        return {
          data: {
            user: user as any,
            session: res.session as any
          },
          error: null
        };
      } catch (err: any) {
        console.error("❌ Login error:", err.message);
        return {
          data: { user: null, session: null },
          error: { message: err.message || "Credenciales inválidas" } as any
        };
      }
    };

    const originalSignOut = client.auth.signOut.bind(client.auth);
    client.auth.signOut = async (options?: any) => {
      if (localStorage.getItem("mock_session") === "true") {
        localStorage.removeItem("mock_session");
        localStorage.removeItem("mock_token");
        localStorage.removeItem("mock_email");
        localStorage.removeItem("mock_name");
        localStorage.removeItem("mock_user_id");
        setTimeout(() => {
          for (const cb of callbacks) {
            cb("SIGNED_OUT", null);
          }
        }, 0);
        return { error: null };
      }
      return originalSignOut(options);
    };

    const originalOnAuthStateChange = client.auth.onAuthStateChange.bind(client.auth);
    client.auth.onAuthStateChange = (callback) => {
      callbacks.add(callback);
      const sub = originalOnAuthStateChange(callback);
      return {
        data: {
          subscription: {
            unsubscribe: () => {
              callbacks.delete(callback);
              sub.data.subscription.unsubscribe();
            }
          }
        }
      };
    };
  }

  return client;
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
